import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Link from 'next/link'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
				<Link
					href={'https://andy-cinquin.com'}
					className={
						'fixed bottom-0 right-0 rounded-tl bg-black/10 p-3 text-xs text-black'
					}
				>
					Developed with ❤️ by{' '}
					<span className={'hover:underline'}>Andy Cinquin</span>
				</Link>
			</body>
		</html>
	)
}
